name: Build React App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1 # Change to your desired Node.js version

      - name: Install dependencies
        run: npm ci
        working-directory: daycare-spa/

      - name: Build the React app
        run: npm run build
        working-directory: daycare-spa/
        env:
          CI: false
