name: Build React App

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1 # Change to your desired Node.js version

      - name: Install dependencies
        run: npm ci
        working-directory: daycare-spa/

      - name: Build the React app
        run: npm run build
        working-directory: daycare-spa/
        env:
          CI: false
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: 'build'  # Path to the build files
          api_location: ''  # Path to API (if applicable)
          output_location: ''  # Path to output files (if applicable)
          enable_for_pr: false  # Change to true if you want to enable PR deployments
          github_token: ${{ secrets.GITHUB_TOKEN }}
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
